configured_endpoints: 47
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/joseph-sofaer%2Fjosephsofaer-e12ad29905b8b1eaf91f4eb81fca2bf0d9ec5d76ebc9d504a23996391d53297e.yml
